version: '3'

services:
  crypto-api:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DB_URL="mysql://root:pass@localhost:3306/crypto"
    env_file:
      - .env
  crypto-db:
    image: 'mysql'
    environment:
      - MYSQL_DATABASE="crypto"
      - MYSQL_ROOT_PASSWORD="pass"
    env_file:
      - .sql-env
    ports:
      - '3306:3306'
    volumes:
      - db-data:/crypto

volumes:
  db-data:
